language: scala

jdk: oraclejdk8

# We define the script in the build matrix
script: echo "No script specified" && false

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.ivy2"
    - "$HOME/.sbt"

before_cache:
  - rm -Rf $HOME/.ivy2/.sbt.cache.lock
  - rm -Rf $HOME/.ivy2/.sbt.ivy.lock

matrix:
  include:
    - stage: Prerequisites (level -2) blended sbt plugins
      script:
        - sh -e scripts/build-prereq.sh sbt-testlogconfig
        - sh -e scripts/build-prereq.sh sbt-jbake
        - sh -e scripts/build-prereq.sh sbt-filterresources

    - stage: Prerequisites (level -1) blended core
      script: sh -e scripts/build-prereq.sh blended

    - stage: Build and Test
      script: sbt ciBuild

    - stage: VerifyPublish
      script: sh -e scripts/verifyPublish.sh

    - stage: Deploy
      script: sh -e scripts/runPublish.sh

stages:
  - name: VerifyPublish
    if: branch = publish AND type = push

  - name: Deploy
    if: branch = publish AND type = push
